const projects = [
  {
    title: "Senior Project",
    category: "Capstone blog",
    description: "A modular, procedurally-loaded game world, documented update by update.",
    url: "https://jmtri7.github.io/SeniorProject/",
    external: true,
    thumbnail: "assets/thumbnails/senior-project.png",
  },
  {
    title: "Orc Slayer",
    category: "Game",
    description: "A top-down dungeon crawler with fireball combat, built in vanilla JavaScript.",
    url: "projects/orc-slayer/",
    thumbnail: "assets/thumbnails/orc-slayer.png",
  },
  {
    title: "Tile World",
    category: "Game",
    description: "A tile-based exploration game with an inventory and item pickups.",
    url: "projects/tile-world/",
    thumbnail: "assets/thumbnails/tile-world.png",
  },
  {
    title: "Render 3D",
    category: "Animation",
    description: "A software 3D rasterizer that projects and shades random primitives, no WebGL.",
    url: "projects/render-3d/",
    thumbnail: "assets/thumbnails/render-3d.png",
  },
  {
    title: "Space Station",
    category: "Animation",
    description: "A simulated star system with orbiting bodies and a drifting shuttle.",
    url: "projects/space-station/",
    thumbnail: "assets/thumbnails/space-station.png",
  },
  {
    title: "Bouncing Boxes",
    category: "Animation",
    description: "Real-time 2D collision detection between randomly generated polygons.",
    url: "projects/bouncing-boxes/",
    thumbnail: "assets/thumbnails/bouncing-boxes.png",
  },
  {
    title: "Projectile Viewer",
    category: "Animation",
    description: "A physics playground for angle-of-attack and projectile trajectories.",
    url: "projects/projectile-viewer/",
    thumbnail: "assets/thumbnails/projectile-viewer.png",
  },
  {
    title: "Damped Wave",
    category: "Visual Maths",
    description: "Circles tracing a sine wave that decays with distance from center.",
    url: "projects/visual-maths/damped-wave/",
    thumbnail: "assets/thumbnails/damped-wave.png",
  },
  {
    title: "Polar Rose",
    category: "Visual Maths",
    description: "An animated polar rose curve with an adjustable amplitude.",
    url: "projects/visual-maths/polar-rose/",
    thumbnail: "assets/thumbnails/polar-rose.png",
  },
  {
    title: "Ripple Field",
    category: "Visual Maths",
    description: "A rippling wave surface driven by a live amplitude slider.",
    url: "projects/visual-maths/ripple-field/",
    thumbnail: "assets/thumbnails/ripple-field.png",
  },
  {
    title: "Sine Scatter",
    category: "Visual Maths",
    description: "Two randomized sine waves rendered as drifting colored dots.",
    url: "projects/visual-maths/sine-scatter/",
    thumbnail: "assets/thumbnails/sine-scatter.png",
  },
];

const seniorProjectVideo = "seniorprojectdemo.mp4";
